version: '3.7'

services:

  api:
    build: .
    image: api
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: admin
      # MONGO_USER: root
      MONGO_USER: basic_user
      MONGO_PASSWORD: hunter2
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      REDIS_PORT: 6379
      REDIS_HOST: redis

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hunter2
      MONGO_INITDB_DATABASE: admin
      MONGO_USER: basic_user
      MONGO_PASSWORD: hunter2

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379


volumes:
  mongo-data: